kind: EncryptionConfig
apiVersion: v1
resources:
  - resources:
      - secrets
    providers:
      - aescbc:
          keys:
            - name: key1
              secret: 1G0H7FjQcQjfDIFnia8AW+ZYOM6YHJDfOX7YfsIVQdc=
      - identity: {}
